default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: parcial_2_development

test:
  <<: *default
  database: parcial_2_test

production:
  <<: *default
  database: parcial_2_production
  username: parcial_2
  password: <%= ENV["LENGUAJES_1_DATABASE_PASSWORD"] %>
